name: yolo_luggage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0 # 将图像缓存
  get: ^4.6.5 # getx
  dio: ^5.1.1 # dio api请求
  shared_preferences: ^2.0.20 # 本地存储
  flutter_animate: ^4.4.0 # flutter 动画
  adaptive_theme: ^3.2.0 # 自动主题
dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^1.3.0 #开发log

flutter:
  uses-material-design: true
  fonts:
    - family: DeYiHei
      fonts:
        - asset: assets/font/deyihei.ttf
  assets:
    - assets/images/